unbind C-b
set -g prefix C-a
bind C-a send-prefix
set -g mouse on

bind r source ~/.config/tmux/tmux.conf
bind g display-popup -d "#{pane_current_path}" -E lazygit
bind q display-popup -d "#{pane_current_path}" -E lazydocker
bind - split-pane #'{pane_current_path}'
bind | split-window -h #'{pane_current_path}'

bind -r Left resize-pane -L 5
bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5
bind -r Right resize-pane -R 5

bind  h select-pane -L
bind  l select-pane -R
bind  k select-pane -U
bind  j select-pane -D

#configração do tmux.config ctr + a + u
 
bind u display-popup -E vim ~/.config/tmux/tmux.conf
bind b display-popup -E btop

#plugins
set  -g @plugin 'tmux-plugins/tpm'
set  -g @plugin 'tmux-plugins/tmux-sensible'
set  -g @plugin 'dracula/tmux'
set  -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

#tmux-continuum
set -g  @continuum-boot 'on'
set -g  @continuum-save-internal '30'

#tmux-ressurect
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-processes 'vim docker gdb node'
set -g @resurrect-dir '$HOME/.config/tmux/history'

#dracula config
set -g @dracula-plugins "cpu-usage ram-usage network continuum time"
set -g @dracula-time-format "%Y-%m-%d %H:%M"
set -g @dracula-military-time true
set -g @dracula-border-constrat true
set -g @dracula-show-flags true
set -g @dracula-clients-minimum 1
set -g @dracula-clients-singular client
set -g @dracula-clients-plural clients
set -g @dracula-cpu-display-load false
set -g @dracula-show-powerline true
set -g status-position top

run '~/.config/tmux/plugins/tpm/tpm'
#prefix + I instala e de um refresh na aba
#prefix + U update nos plugins
#prefix + alt + u remove plugisn
#salvar secao prefix + crtl + s
#carregar secao prefix + crtl + l
